kind: pipeline
name: {PROJECT_NAME}

trigger:
  branch:
    - {BRANCH}
  event:
    - push

volumes:
  - name: docker_daemon
    host:
      path: /var/run/docker.sock
  - name: docker_cache
    host:
      path: /mnt/drone-docker

steps:
  - name: tag
    image: alpine
    commands:
      - apk add --no-cache git
      - echo "export BRANCH="$(git rev-parse --abbrev-ref HEAD) > .tag
      - echo "export COMMIT="$(git rev-parse --short HEAD) >> .tag
      - cat .tag

  - name: build laravel
    image: docker:dind
    environment:
      REGISTRY_USER:
        from_secret: docker_username
      REGISTRY_PASS:
        from_secret: docker_password
    volumes:
      - name: docker_cache
        path: /var/lib/docker
      - name: docker_daemon
        path: /var/run/docker.sock
    commands:
      - source .tag
      - docker login -u $REGISTRY_USER -p $REGISTRY_PASS registry.vivifyideas.com
      - docker build -t registry.vivifyideas.com/{NAMESPACE}/{REPOSITORY}:$BRANCH --pull=true .
      - docker push registry.vivifyideas.com/{NAMESPACE}/{REPOSITORY}:$BRANCH
      - docker image prune -f

  - name: build laravel
    image: docker:dind
    environment:
      REGISTRY_USER:
        from_secret: docker_username
      REGISTRY_PASS:
        from_secret: docker_password
    volumes:
      - name: docker_cache
        path: /var/lib/docker
      - name: docker_daemon
        path: /var/run/docker.sock
    commands:
      - source .tag
      - docker login -u $REGISTRY_USER -p $REGISTRY_PASS registry.vivifyideas.com
      - docker build -f Dockerfile-web -t registry.vivifyideas.com/{NAMESPACE}/{REPOSITORY}:$BRANCH --pull=true .
      - docker push registry.vivifyideas.com/{NAMESPACE}/{REPOSITORY}:$BRANCH
      - docker image prune -f

  - name: deploy
    image: alpine
    commands:
      - apk add --no-cache curl
      - source .tag
      - sh deploy.sh

  - name: slack
    image: plugins/slack
    when:
      status: [ success, failure ]
    settings:
      webhook:
        from_secret: slack_webhook
      channel: {SLACK_CHANNEL}

