version: '3'
services:

  laravel:
    build:
      context: .
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    container_name: laravel
    volumes:
      - uploads:/app/public/uploads
      - build:/app/public/build
      - storage-app:/app/storage/app/public
      - logs-app:/app/storage/logs
      - phpsessions:/tmp

  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    container_name: web
    deploy:
     restart_policy:
       condition: on-failure
    depends_on:
      - laravel
    environment:
      - NGINX_SERVER_NAME=_
      - NGINX_PORT=80
      - NGINX_SECURE_PORT=443
      - NGINX_MAX_BODY=100M
      - NGINX_SSL_CERT=/certs/certificate.pem
      - NGINX_SSL_KEY=/certs/privatekey.pem
      - NGINX_SSL_DH=/certs/dh.pem
    command: /bin/bash -c "envsubst \"`for v in $$(compgen -v);do printf '$${%s} ' $$v;done`'\" < /etc/nginx/conf.d/vhost.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    ports:
      - 80:80
      - 443:443
    volumes:
      - uploads:/app/public/uploads
      - build:/app/public/build

  redis:
    container_name: redis
    image: "redis:alpine"
    deploy:
      restart_policy:
        condition: on-failure

  beanstalk:
    container_name: beanstalk
    image: "jonbaldie/beanstalkd"
    deploy:
      restart_policy:
        condition: on-failure
  # es:
  #   image: docker.elastic.co/elasticsearch/elasticsearch:6.2.4
  #   environment:
  #     - network.host=0.0.0.0
  #     - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
  #   ulimits:
  #     memlock:
  #       soft: -1
  #       hard: -1
  #   volumes:
  #     - esdata:/usr/share/elasticsearch/data

  db:
    image: mariadb:10.2
    container_name: db
    deploy:
      restart_policy:
        condition: on-failure
    environment:
        MYSQL_DATABASE: laravel-boilerplate
        MYSQL_USER: laravel
        MYSQL_PASSWORD: laravel
        MYSQL_ROOT_PASSWORD: root
    ports:
      - 3306:3306
    volumes:
        - mariadbdata:/var/lib/mysql


  portainer:
    image: portainer/portainer
    deploy:
      placement:
        constraints: [node.role == manager]
    environment:
      - ADMIN_USERNAME=admin
    command: -H unix:///var/run/docker.sock
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainerdata:/data
    ports:
      - 9000:9000

volumes:
  #esdata:
  mariadbdata:
  portainerdata:
  uploads:
  build:
  storage-app:
  logs-app:
  phpsessions: